In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [11]:
arr.shape

(2, 2)

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [ ]:
arr.ndim

2

In [14]:
print(arr.size)

4


In [15]:
arr = np.array([1, 2, 3], dtype=float)

print(arr)

[1. 2. 3.]


In [17]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [24]:
np.random.rand(3,3)

array([[0.67831048, 0.23807715, 0.95880398],
       [0.18420992, 0.79128471, 0.32024575],
       [0.48350781, 0.43915945, 0.53278396]])

In [25]:
np.random.randint(1,10,(2,3))

array([[5, 9, 1],
       [9, 4, 2]], dtype=int32)

In [26]:
arr = np.array([10, 20, 30])
arr = np.array([10, 20, 30])

In [27]:
arr = np.array([1, 2, 3])

print(arr + 10)

[11 12 13]


In [28]:
# matrix multiplication
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(a @ b)

[[19 22]
 [43 50]]


In [31]:
arr=np.random.randint(1,20,(3,3))
print(arr)
arr.T

[[12  7 12]
 [ 6 14  5]
 [17  4  4]]


array([[12,  6, 17],
       [ 7, 14,  4],
       [12,  5,  4]], dtype=int32)

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr.flatten())

[1 2 3 4 5 6]


In [39]:
# axios=0 -> column wise

# Axis=1 -> row wise

arr1=np.array([[1,2,3,4],[5,6,7,8]])
# arr2=np.array([3,4,5,6])

print(arr1)
print(np.sum(arr1,axis=0))
print(np.sum(arr1,axis=1))



[[1 2 3 4]
 [5 6 7 8]]
[ 6  8 10 12]
[10 26]


In [41]:
arr = np.array([1, 2, 3, 4, 5])

print(arr > 3)

[False False False  True  True]


In [42]:
print(arr[arr > 3])

[4 5]
