Linear Regression is not suitable for classification because it predicts continuous values, while classification requires discrete classes (e.g., 0 or 1).

Example

Suppose we want to classify whether a student passes:

Hours Studied	Pass
1	0
2	0
3	0
4	1
5	1


A linear regression model might learn:

y=0.3x−0.8

Now for:

x = 2 → y = -0.2
x = 4 → y = 0.4
x = 7 → y = 1.3

Problems
1. Predictions can be less than 0 or greater than 1

For classification, probabilities should be between 0 and 1.

Linear regression can predict:

-0.5
1.7
2.3

These are not valid probabilities.

2. Sensitive to outliers

A few extreme points can significantly change the regression line and affect classification decisions.

3. Decision boundary is not probabilistic

Classification often needs:

"What is the probability that this belongs to class 1?"

Linear regression doesn't naturally provide valid probabilities.

Why Logistic Regression Works

Instead of a straight line, logistic regression applies a sigmoid function:

p=
1+e
−z
1
	​


This converts any number into a value between 0 and 1.

Example:

z = -10 → p ≈ 0
z = 0 → p = 0.5
z = 10 → p ≈ 1

Then:

p ≥ 0.5 → Class 1
p < 0.5 → Class 0
Visual Intuition

Linear Regression

Class 0    Class 1

0----0----1----1

---------/---------
        line

Predictions can go below 0 or above 1.

Logistic Regression

Probability

1.0 |        ______
    |      /
0.5 |----/
    |  /
0.0 |/
    +----------------

The S-shaped curve keeps probabilities between 0 and 1.

Interview Answer

Linear Regression is not used for classification because it predicts continuous values and can produce outputs outside the valid probability range [0,1]. Logistic Regression uses a sigmoid function to convert predictions into probabilities between 0 and 1, making it suitable for classification tasks.

Performance Metrics:

1. confusion matrix
2. Accuracy
3. Precision
4. Recall
5. F_Beta score

A Confusion Matrix is used to evaluate how well a Logistic Regression classifier performs.

For a binary classification problem, it looks like this:

| Actual \ Predicted | Positive (1)        | Negative (0)        |
| ------------------ | ------------------- | ------------------- |
| Positive (1)       | True Positive (TP)  | False Negative (FN) |
| Negative (0)       | False Positive (FP) | True Negative (TN)  |


Example

Suppose we have the following confusion matrix:

| Actual \ Predicted | 1  | 0  |
| ------------------ | -- | -- |
| 1                  | 50 | 10 |
| 0                  | 5  | 35 |
Metrics from Confusion Matrix
Accuracy
Accuracy=TP+TN+FP+FN//TP+TN
	​

Accuracy=
50+35+5+10//50+35=100//85=85%
Precision
Precision=
TP+FP//TP
	​

Precision=
50+5//50=0.909

Recall (Sensitivity)
Recall=
TP+FN//TP
	​

Recall=
50+10//50=0.833

F1 Score
F1=Precision+Recall//2×Precision×Recall
	​

F1=0.87

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification



In [4]:
# Creating dataset

X,y=make_classification( n_samples=1000,n_features=10,n_classes=2,random_state=42)

X.shape,y.shape

((1000, 10), (1000,))

In [5]:
X=pd.DataFrame(X)
y=pd.DataFrame(y)



In [6]:
X.head()

,0,1,2,3,4,5,6,7,8,9
0,0.964799,-0.066449,0.986768,-0.358079,0.997266,1.181890,-1.615679,-1.210161,-0.628077,1.227274
1,-0.916511,-0.566395,-1.008614,0.831617,-1.176962,1.820544,1.752375,-0.984534,0.363896,0.209470
2,-0.109484,-0.432774,-0.457649,0.793818,-0.268646,-1.836360,1.239086,-0.246383,-1.058145,-0.297376
3,1.750412,2.023606,1.688159,0.006800,-1.607661,0.184741,-2.619427,-0.357445,-1.473127,-0.190039
4,-0.224726,-0.711303,-0.220778,0.117124,1.536061,0.597538,0.348645,-0.939156,0.175915,0.236224


In [7]:
y.head()

,0
0,0
1,1
2,1
3,0
4,1


In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [9]:
X_train.shape

(700, 10)

In [10]:
from sklearn.linear_model import LogisticRegression

logistic=LogisticRegression()

In [11]:
logistic.fit(X_train,y_train)

/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [15]:
y_pred=logistic.predict(X_test)

y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [16]:
# Performance metircs

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report



In [17]:
score=accuracy_score(y_test,y_pred)

score

0.8466666666666667

In [18]:
cm=confusion_matrix(y_test,y_pred)

cm

array([[118,  17],
       [ 29, 136]])

In [21]:
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression

params = {
    'penalty': ['l1', 'l2','elasticnet'],
    'C': [100, 10, 1, 0.1, 0.01],
    'solver': ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
}

cv = StratifiedKFold()

logistic = LogisticRegression()

model = GridSearchCV(
    estimator=logistic,
    param_grid=params,
    scoring='accuracy',
    cv=cv,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Best Parameters:", model.best_params_)
print("Best Accuracy:", model.best_score_)

/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticn

Best Parameters: {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Best Accuracy: 0.8785714285714287


 of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/jyothiksandeep/Desktop/jyothik/Project_Space/machine_learning/venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf inst

In [28]:
model


,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",LogisticRegression()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'C': [100, 10, ...], 'penality': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",StratifiedKFo...shuffle=False)
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose ver

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)

cm=confusion_matrix(y_test,y_pred)

report=classification_report(y_test,y_pred)

print(accuracy)
print(cm)
print(report)


0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



In [36]:
# RandomizedCV

# It will select random parameters


In [41]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=3,
    n_classes=3,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)



In [42]:
X_train.shape

(700, 10)

In [43]:
X_train

array([[-0.04817869, -0.5239488 ,  0.57244531, ...,  1.97234448,
         0.94964306,  0.46425124],
       [ 1.15419767,  0.70156291, -0.93100171, ...,  0.31444459,
         2.66009185, -0.35895839],
       [-0.32575606, -0.07354436,  0.25062823, ..., -0.62742073,
        -0.66449672,  1.22885655],
       ...,
       [-0.36703399, -0.50884119, -0.00407284, ...,  0.64189412,
        -1.04867144, -1.02969624],
       [-0.26990399,  0.72628752, -0.56155775, ..., -1.78115841,
         0.11360534, -2.23046802],
       [-0.09621943, -1.15270821,  0.21000831, ..., -1.67176127,
        -0.4187543 ,  2.71033164]], shape=(700, 10))

In [44]:
y_train

array([2, 1, 2, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 2, 1, 2, 2, 1, 1,
       0, 0, 2, 1, 2, 1, 2, 0, 0, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 1,
       1, 0, 1, 0, 2, 2, 0, 0, 2, 0, 1, 0, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 2,
       1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 0,
       2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 2, 0, 1, 2, 2, 0, 0, 2, 0, 1,
       1, 1, 0, 0, 2, 0, 2, 2, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 2,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 2, 1,
       0, 2, 1, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 2, 2, 0, 2, 1,
       1, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 1,
       1, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0,
       2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 2, 0,
       1, 2, 2, 0, 1, 2, 0, 2, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       0, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 1, 2, 1,

In [47]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()



In [48]:
model.fit(X_train,y_train)



,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default sol

In [49]:
y_pred=model.predict(X_test)


In [50]:
y_pred

array([2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 1, 1, 2, 1,
       0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 2, 2, 2, 2, 0, 2, 1,
       2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2,
       0, 2, 1, 1, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 1, 0, 1, 2, 2, 0,
       2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 2,
       1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0,
       1, 2, 2, 1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 0,
       1, 2, 2, 0, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 2, 1,
       2, 2, 1, 1, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 2,
       1, 1, 0, 0, 0, 1, 2, 1, 0, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 1,
       2, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1,
       1, 2, 2, 0, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 1, 1, 0, 0,
       1, 0, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2])

In [52]:
from sklearn.metrics import accuracy_score

accuracy=accuracy_score(y_test,y_pred)


print(accuracy)

0.6766666666666666
